### ISSUE TITLE
Please add license note on transferring licence from GPL to MIT

### ISSUE THREAD

**Issue by prepare** [ForNeVeR/wpf-math#110]
Hello,

I'm interested in rendering Math glyph (I have a plan to solve this =>https://github.com/LayoutFarm/Typography/issues/20). And your lib look great!,

from [readme](https://github.com/ForNeVeR/wpf-math/blob/master/README.md) 

> The library was originally ported from the JMathTex project.

But I can't use the copyleft-code in my lib (since the original  is still in GPL).

from your license notes on page:

> ... The project code is licensed under the terms of MIT license. The original resources from JMathTeX (DefaultTexFont.xml, GlueSettings.xml, PredefinedTexFormulas.xml, TexFormulaSettings.xml, TexSymbols.xml) are taken from the GPLv2-distributed JMathTeX, 
**but JMathTeX authors have granted permission to redistribute these resourses under the MIT license.**

---

Do you have a note (or link/ declaration) 
from the original author of JMathTeX 
with explicit  license transfer declaration ?
( ...  _JMathTeX authors have granted permission to_ ...).

If yes, please add that too. :)

If not, just close this issue ;)

Thank you

**Comment by alexreg** [comment]
We can't exactly offer a copy of a signed affidavit, but [this previous issue](https://github.com/ForNeVeR/wpf-math/issues/87) will hopefully address the point!

**Comment by ForNeVeR** [comment]
@alexreg, how do you think: maybe I should place that email fragment somewhere in the documentation? 

People keep being confused by my license notes and keep asking the same thing. It's a sign that we haven't made the information available for them.

**Comment by ForNeVeR** [comment]
As a side note: I hope that in future, we'll be able to get rid of all the XML files we've inherited from JMathTeX project, and probably @prepare's [Typography](https://github.com/LayoutFarm/Typography) library will help us.

**Comment by alexreg** [comment]
@ForNeVeR I think for most people the simple declaration (like we have now) will be enough. However, for some that are especially concerned about legalities, it clearly isn't. Probably the best solution is creating a wiki page (maybe a FAQ page, or a Licence page), and linking to that from the existing section in the README. This wiki page could contain something similar to what you have already in that response to the issue.

**Comment by ForNeVeR** [comment]
Oh, that's a huge issue. @prepare, thanks for raising awareness of that fact.

I've taken a look at the JMathTeX sources and, indeed, they are very similar to ours. Large pieces of WPF-Math code are a translation of original Java code to C#.

We haven't discussed this matter with Dr. Coolsaet. I guess at the moment I have to pause all other work on the project and have a discussion with him.

Thus I'm reopening the issue.

**Comment by ForNeVeR** [comment]
Everything is alright, guys. See #177.
