### ISSUE TITLE
Big operator rendering problem inside `\frac`

### ISSUE THREAD

**Issue by ProSimPC** [ForNeVeR/wpf-math#119]
Hello,

First I would like to say WpfMath is a wonderful library. I had searched something like this for a long time.

I went into a small rendering bug when using this kind of formula: \frac{1}{\sum{a}}
The "a" is not at the right place but looks like a superscript. It happens only when the sum is under a fraction.

Best regards,
Pierre

**Comment by ForNeVeR** [comment]
Here's how it looks:

- without `\frac`: 
![image](https://user-images.githubusercontent.com/92793/37874916-12eda2fe-3062-11e8-9fab-8b551755f569.png)

-with `\frac`:
![image](https://user-images.githubusercontent.com/92793/37874921-218fadd4-3062-11e8-828f-abfb78773de4.png)

Obviously something's wrong on our side.

**Comment by ForNeVeR** [comment]
Also, it works the same for every "big operator" (`\int`, `\prod`, etc.)

**Comment by ForNeVeR** [comment]
*NOTE FOR IMPLEMENTORS*: When fixing that, be careful not to break cases such as `\frac{\sum^a_bx}{2}`. With current implementation, it works okay. Although, it was broken by my initial naïve fix.

**Comment by ForNeVeR** [comment]
@ProSimPC, looks like I was able to fix the bug. While other maintainers are reviewing my PR, could you please tell me if it's critical for you? If it is, we could release a fix version (and push it onto NuGet) right after merging the PR.

**Comment by ProSimPC** [comment]
@ForNeVeR, it's nice to see you've found the source of the bug. It not critical at all for me, I will wait for the next release.
