### ISSUE TITLE
\thinspace exception

### ISSUE THREAD

**Issue by AndrewXS** [ForNeVeR/wpf-math#139]
Start the WpfMath.Example project.
Clear the starting formula in the textbox.
Enter "\\,"
An exception is thrown in TexPredefinedFormulaParser.cs

**Comment by Bez99** [comment]
Are you sure this is an issue. I did exactly what you did and no Exceptions were thrown.

**Comment by AndrewXS** [comment]
I'm running the WpfMath 0.5 code from 2018-05-08. Debug build in VS Enterprise 2017 Version 15.5.6. Just tried again, same problem. You entered the backslash and the comma?

**Comment by AndrewXS** [comment]
No, not a period. However, I just tried all of the spacing commands ( \, \; \: \! ), and they cause the exception.

The attached image shows the exception with \;. (The source is {\;})

![wpfmath_exception](https://user-images.githubusercontent.com/40889744/42620117-8bf4bb5a-85a9-11e8-8d6e-1ea308d2cbae.png)
