### ISSUE TITLE
Extensible delimiters (\left and \right)

### ISSUE THREAD

**Issue by gsomix** [ForNeVeR/wpf-math#14]
Full brace list we need to support:
- [x] `\left.` `\right.` (empty delimiter)
- [x] `\left(` `\right)`
- [x] `\left[` `\right]`
- [x] `\left\{` `\right\}`
- [x] `\left<` `\right>`
- [x] `\left|` `\right|`

### Plan

- [x] take a look at Java implementation — _at least JLatexMath seems to support those delimiters ~ F_
- [x] implement delimiters as a resizable characters (i.e. don't split them into top / top-middle / etc. parts yet)
- [x] add full support with splitting the characters into parts — _it suddenly turned out that we already have those_

**Comment by ForNeVeR** [comment]
I think that we'll need to store brace stack somewhere when interpreting the formula, and try to keep their sizes equal.

**Comment by alexreg** [comment]
This is definitely a feature that should be prioritised. I'm not sure if the Java library I ported from handled this at all (actually there were two Java libraries; one for plain TeX and one for LaTeX), but it's worth a check. If not, having a look at the LaTeX source code may be informative.

**Comment by ForNeVeR** [comment]
Aha, it seems like [jlatexmath](https://github.com/opencollab/jlatexmath) have support for `\left` and `\right`.

**Comment by ForNeVeR** [comment]
Just dumping what I've found regarding this task so far.

It seems that we have the atom definition for the brace-enclosed formula; it's called [`FencedAtom`](https://github.com/ForNeVeR/wpf-math/blob/4f9ad0f0ba365bfe4c5d76446ae020bf23cb0ddc/WpfMath/FencedAtom.cs).

It looks like that `FencedAtom` isn't used in the current code, but it could be exactly what we need. I plan to add the support for `\left` and `\right` commands into [`TexFormulaParser.ProcessCommand` method](https://github.com/ForNeVeR/wpf-math/blob/f1c61cf32952146b8b9418bc6e3783f71c1a8d61/WpfMath/TexFormulaParser.cs#L242). It seems like that won't be very hard: just parse the formula part before the corresponding `\right` delimiter and enclose it in `FencedAtom` (probably we'll want to keep that stack somewhere; we'll see).

I also want to add unit tests for the parser; I'll file another issue about that.

**Comment by alexreg** [comment]
Good work on this. I haven't looked at the implementation yet, but I'm slightly concerned that most of the brackets are implemented except for `\left|`. Did you not do this in a generic way?

**Comment by ForNeVeR** [comment]
Ah, that's a long story. My initial implementation had some flaws, and I _thought_ there were problems with `\left|`. Actually there're none.

The delimiters are implemented in a generic way (because there's already a metadata on delimiters), `\left|` is working. I'll mark it now.

`\left.` and `\right.` aren't working currently exactly because there aren't any metadata about them. I think we'll handle them in a special way or simple declare as proper delimiters; will decide later.

**Comment by alexreg** [comment]
Oh, right. Fair enough then!

**Comment by ForNeVeR** [comment]
Oh, that's interesting. `|` is considered as an opening delimiter only. Look:
![image](https://cloud.githubusercontent.com/assets/92793/23337079/37e4f0da-fc15-11e6-9a82-40ff31ff3959.png)
![image](https://cloud.githubusercontent.com/assets/92793/23337080/42fc4932-fc15-11e6-87a4-5e57e7735c38.png)

**Comment by alexreg** [comment]
Good spot. That was definitely the problem.
