### ISSUE TITLE
_ doesn't render inside \text

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#141]
![default](https://user-images.githubusercontent.com/92793/42731780-1057fbc6-881d-11e8-884d-1e551e008bb9.png)
![default](https://user-images.githubusercontent.com/92793/42731782-15c0d8bc-881d-11e8-85b8-6063440a3872.png)

**Comment by ForNeVeR** [comment]
I think that `\text{\_}` should render an underscore. For now I have absolutely no way to render an underscore inside of `\text`.

**Comment by B3zaleel** [comment]
Maybe you could include a Unicode command(\uni) which works only if the text style is "text" ,the next non-whitespace character is plus. After the plus sign and the hexcode, there should be a whitespace to signal the end of the code. Try to convert the hex code to an integer and convert the integer to a character. Return a character atom based on the converted character if the character is less than thppthe maximum value of an unsigned short. I believe that would work, along with the other code points that aren't on a standard keyboard.

**Comment by Happypig375** [comment]
@B3zaleel 
Note: Supporting arbitrary codepoints would need you to look out for Combining Marks and Variation Sequences.

**Comment by ForNeVeR** [comment]
Any kind of "Unicode" command looks like a separate feature, please file another issue about that. Also we'd need to find out if any standard LaTeX distribution already supports that kind of command.

**Comment by ForNeVeR** [comment]
Yes, we can define new commands if we feel that our users will use WPF-Math's TeX dialect in some uncommon ways (e.g. we could add transparency support etc.). Although, I can't yet see the issue you're trying to solve with your "Unicode" command.

**Comment by B3zaleel** [comment]
TeX has the command *\\char{character code in decimal notation}*. Which can be used if one needs a special symbol that hasn't been defined.

**Comment by Happypig375** [comment]
[The \char command takes a _Glyph Index_, not a codepoint.](https://tex.stackexchange.com/a/255728). It is used for where some glyphs cannot otherwise be obtained. However, with your unicode command, it will be very easy to get a codepoint without a corresponding glyph in the current font. How will you deal with that?

**Comment by ForNeVeR** [comment]
A side note: `\text{_}` should just work without any kind of magic commands: http://www.texpaste.com/n/twxhpxfl
