### ISSUE TITLE
Newline and font size

### ISSUE THREAD

**Issue by balsaknez** [ForNeVeR/wpf-math#149]
Is it possible to render a newline? 
When I type \r\n or \n, it renders a space instead of a newline.

Is it possible to set font size of text?

**Comment by balsaknez** [comment]
Thanks, but that doesn't work either

**Comment by Happypig375** [comment]
Then it might not be implemented.

**Comment by ForNeVeR** [comment]
For now, neither of that was implemented. Hopefully we'll be able to implement them sooner or later. Best you can do to help is to implement the feature yourself and send a pull request :)

But mentioning that it is an important feature for you is already good enough, I'll prioritize the task.

**Comment by hbadi** [comment]
Hello, i tried everything to display multiline equations. Is it possible with wpfmath ?

**Comment by ForNeVeR** [comment]
@hbadi, for now, you could try a matrix:
![image](https://user-images.githubusercontent.com/92793/70460939-85469c00-1ac8-11ea-9176-a1f7757a6403.png)

Will that work for you?

A proper newline implementation (in form of a freely-available `\\` command) is in the works right now.

**Comment by ForNeVeR** [comment]
Newline (aka `\\` command) support has been merged in #222.

As discussion here was mostly about that feature, I've decided to close this issue and open a new one focused on font sizes: #239.

**Comment by cvdevol** [comment]
The best you can do regarding font size is to apply a ScaleTransform to the FormulaControl. This will increase/decrease the size of entire formula.
