### ISSUE TITLE
Why don't we have a develop branch?

### ISSUE THREAD

**Issue by B3zaleel** [ForNeVeR/wpf-math#167]

**Comment by ForNeVeR** [comment]
Here we use a simplified "git-flow" approach: `master` is essentially a "develop" branch, and releases are just tagged commits from `master` (where in git-flow you have a dedicated branch for releases).

I'm sorry for my responsiveness on latest developments in a couple of months, I'll become more active soon (likely in about a week from today).

**Comment by alexreg** [comment]
That’s not git-flow at all, it’s just the standard model. :-)

**Comment by ForNeVeR** [comment]
I believe you got the answer. Feel free to ask more!
