### ISSUE TITLE
Parenthesis instead of square brackets

### ISSUE THREAD

**Issue by lellid** [ForNeVeR/wpf-math#171]
`\lbrack` and `\rbrack` are rendered to left and right parentheses `()`, but they should be rendered to left and right square brackets `[]`.

Moreover, the parser parses a left parenthesis `(` to a `SymbolAtom` containing the name lbrack. I guess the error above arises from the confusion about what lbrack and rbrack are.

**Comment by lellid** [comment]
Fixed it! I could write a PDR, but I have different VS2017 settings, and its only a few lines in 4 different files, so please have a look at [this commit](https://github.com/Altaxo/Altaxo/commit/60f8ca7b2da9ea057ad4a129ea707f3f31a3746a).

Let me know if this is fixing it!

**Comment by ForNeVeR** [comment]
Thanks, I'll take a look.
