### ISSUE TITLE
\binom command

### ISSUE THREAD

**Issue by troelschristensen** [ForNeVeR/wpf-math#174]
Hi @ForNeVeR 

Happy New Year.

I'm programming some math assignments regarding vectors, and would appreciate, if your code could do this:
`\vec{n} = \binom{2}{3}` showing this
![image](https://user-images.githubusercontent.com/16334255/50735575-ac5a6680-11b1-11e9-9d20-4acddf3e6f7a.png)

Right now I am using `\vec{n} =  \left( \frac{2}{3}\right)` showing this
![image](https://user-images.githubusercontent.com/16334255/50735602-3276ad00-11b2-11e9-9d2d-6b09f28dd2bf.png)

 but that is just a work around and surely not the best way.

Kind regards.
Troels Christensen

**Comment by ForNeVeR** [comment]
Unfortunately, this feature isn't supported by WPF-Math today.

There's a couple of technically similar requests: #81 (`\array`) and #100 (where you've even participated).

These issues will be the focus for the current development iteration.

**Comment by troelschristensen** [comment]
Great @ForNeVeR. Thank you for the reply. 
It’s just because the fact that I am developing some things right now, and on that matter I am curious about, if wpf-math is going to support these functions. But great to know, that you are looking on that in the current development iteration.
Kind regards, Troels

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by troelschristensen** [comment]
Any news on the next iteration, @ForNeVeR ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ForNeVeR** [comment]
Currently I'm slowly working on #155 which will likely become a basis of implementing this feature.

**Comment by troelschristensen** [comment]
Ok @ForNeVeR. Thank you for the news update.👍Any eta on the next update? (Eg 0.7?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ForNeVeR** [comment]
@troelschristensen why exactly are you asking? If you need a new version with the stuff already in master (a couple of minor bug fixes mostly), then I could package it right now.

If you're interested in a version that will include `\matrix` support (and thus you'll be able to use vectors, even if not with `\binom` command), then I've planned it to be finished till 1th of August.

But, you know, WPF-Math is open-source and I'm working on it out of pure altruism, so it could be delayed (even if I try to not do that).

**Comment by troelschristensen** [comment]
Hi @ForNeVeR. And you are doing a great job.🙌 Just wanted to know.🤷‍♂️😊 Yes It’s Open Source, but I don’t believe, that I can do those things.🤷‍♂️I wait for the update.👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ForNeVeR** [comment]
@troelschristensen, for your information: I've just merged #155 (thanks to our great contributors).

For now, you'll be able to create the markup you need with `\vec{n}=\left(\matrix{1\\2}\right)`:

![image](https://user-images.githubusercontent.com/92793/63637713-dbbed480-c6a9-11e9-9cd8-282462eac6dc.png)

I'll publish a fresh release that includes this feature soon (in 24h).

There're plans to add a `\binom` command, too, but maybe in the next version (so I won't close the issue yet) :)

**Comment by troelschristensen** [comment]
Great news @ForNeVeR 🙌🙌 Looking forward to the next release then. Great work. Thank you for the info.👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
