### ISSUE TITLE
\frac{} (with empty radicand) crashes with nullreference exception.

### ISSUE THREAD

**Issue by sskodje** [ForNeVeR/wpf-math#176]
I have previously submitted at fix for this, but it seems to have been deleted in commit a6e008e1c9cb053816aed05f51793e6b159b567f .

**Comment by ForNeVeR** [comment]
Wow thanks! That's what could happen if I don't cover the code with unit tests. Will be fixed soonish, after we sort out #110.

**Comment by ForNeVeR** [comment]
It is already fixed in master, but I'll go ahead and write a test for it.
