### ISSUE TITLE
Need to create EmptyAtom?

### ISSUE THREAD

**Issue by rstm-sf** [ForNeVeR/wpf-math#207]
<details>
  <summary>Preface: excerpts from the #205 </summary>

> 
> 
> > WpfMath.Tests.ParserExceptionTests.\mathrm{} should throw exn
> 
> @ForNeVeR, why do you think that an exception should occur in the case of `\mathrm{}`?
@rstm-sf 

> That's a good question, actually. I think the code was written that way originally, and my tests just asserted the existing behavior. I agree that we should fix the current behavior to be more compliant with the standard TeX engines.
@ForNeVeR 

---

> After [parsing](https://github.com/ForNeVeR/wpf-math/blob/98b46892464e3c6380dfb0127157380d91dcd286/src/WpfMath/TexFormulaParser.cs#L476) the `remainingString`, the `remaining.RootAtom` (line 480) is null in case `\colorbox{red}{}` (I think the same case with `\color{red}{}`). It as a result leads to exception ([`atom`](https://github.com/ForNeVeR/wpf-math/blob/98b46892464e3c6380dfb0127157380d91dcd286/src/WpfMath/Atoms/DummyAtom.cs#L10) is null). I thought `NullAtom` was created for this.
@rstm-sf 

> Thanks, now I get what the error is. I don't think that `NullAtom` was created for this, but could/should it be used for this? Well, maybe? What alternatives do we have?
@ForNeVeR 

> Maybe write some EmptyAtom? But you need to he was really is for all 'empty'.
@rstm-sf 

> Well, `NullAtom` seems empty enough for our purposes :)
@ForNeVer

> Actually there needs to be something like that `new StrutBox(1, 1, 0, 0)`
@rstm-sf 

> Why do you think we need that?
@ForNeVeR 

>Because I get the following result  and did not think about the size
  ![](https://user-images.githubusercontent.com/2669927/66179105-619e4a00-e670-11e9-901e-3b12cef583e9.png)
@rstm-sf 

> Hm. I'm not sure if we really want to follow this pattern from the image. Let's make it empty for now.
> 
> If any user will complain about the empty block rendering as an empty block, we may reconsider :)
@ForNeVeR 

---

> We should not do `RootAtom = new EmptyAtom()`. Must either leave `RootAtom = null` or create `NullAtom` and `EmptyAtom`.
@rstm-sf 

</details>

---

We need to split `NullAtom` into `NullAtom` ( :) ) and `EmptyAtom`.

<details>

If I change line [Radical.cs#L19](https://github.com/rstm-sf/wpf-math/blob/f8c610a23d5ea9085e2986f69b281d8735ea2213/src/WpfMath/Atoms/Radical.cs#L19) to 

```c#
this.BaseAtom = new RowAtom(source, baseAtom);
```

I will get the following
![](https://user-images.githubusercontent.com/2669927/66703590-e9452200-ed1c-11e9-8c03-3f62eccea2e8.png)

Further, If I change line [Radical.cs#L19](https://github.com/rstm-sf/wpf-math/blob/f8c610a23d5ea9085e2986f69b281d8735ea2213/src/WpfMath/Atoms/Radical.cs#L19) to 

```c#
this.BaseAtom = new RowAtom(source, baseAtom ?? new NullAtom());
```

And I change line [NullAtom.cs#L11](https://github.com/rstm-sf/wpf-math/blob/f8c610a23d5ea9085e2986f69b281d8735ea2213/src/WpfMath/Atoms/NullAtom.cs#L11) to

```c#
protected override Box CreateBoxCore(TexEnvironment environment) => new StrutBox(1, 1, 0, 0);
```

I will get the following
![](https://user-images.githubusercontent.com/2669927/66703764-9d937800-ed1e-11e9-9178-ba267bcb134e.png)

In LaTeX
![](https://user-images.githubusercontent.com/2669927/66703912-1a732180-ed20-11e9-85a5-bd1b2c157af7.png)

</details>

---
Afterword

If I understand correctly, then `RootAtom = null` is needed in order not to show what is not processed in LaTeX (for example, whitespaces). But this approach hits `null` checks (for example, [AccentedAtom.cs#L55](https://github.com/ForNeVeR/wpf-math/blob/0d788e639d25e24509756809cda193f14e1f4724/src/WpfMath/Atoms/AccentedAtom.cs#L55)) and not in every case it is considered (for example, sometimes the parser crashes by empty).

Therefore, we must now decide how to move on:
- Case 0: we stick with `RootAtom = null` and refactor the code based on this (started in [this commit](https://github.com/ForNeVeR/wpf-math/pull/205/commits/ce19b4e71bd9fde361155f79d7235e34d5ec7eed )).
- Case 1: we replace `RootAtom = null` with `RootAtom = NullAtom` and refactor the code based on this.

Each option has its pros and cons in refactoring, as it seemed to me that the current code is based on these two ideologies. And I don’t understand what the choice of this or that path will lead to.

**Comment by ForNeVeR** [comment]
Could you please explain how `NullAtom` will differ from `EmptyAtom`?

**Comment by rstm-sf** [comment]
If we now assume that `NullAtom` and `EmptyAtom` are the same, then when you change the behavior of `CreateBoxCore(TexEnvironment)` to return `new StrutBox(1, 1, 0, 0)`, we get that our formulas will begin to contain extra indentation due to the fact that `CreateBoxCore(TexEnvironment) != StrutBox(0, 0, 0, 0)`. Sorry, I did not save an example based on this belief (maybe, of course, I was mistaken somewhere and therefore got such a result). But this can be traced on the example of the situation with the root.

Also, we need `NullAtom`, as I understand it. For example, it is being added [here](https://github.com/ForNeVeR/wpf-math/blob/3d700b1109d32384985b9966f39107476cff5fc0/src/WpfMath/Parsers/Matrices/MatrixCommandParser.cs#L92). This is probably connected somehow with an algorithm for which it is necessary that the lines be aligned in length.

**Comment by ForNeVeR** [comment]
And why do we need to change the behavior of `NullAtom.CreateBoxCore`? Honestly, I'm still not convinced that it's important.

**Comment by rstm-sf** [comment]
> And why do we need to change the behavior of `NullAtom.CreateBoxCore`? Honestly, I'm still not convinced that it's important.

I agree with it. But I do not agree to rename it `EmptyAtom`. `NullAtom` is needed in order to display the non-displayable.

**Comment by rstm-sf** [comment]
Question: Should there be `NullAtom` or `EmptyAtom` [here (AccentedAtom.cs#L55)](https://github.com/ForNeVeR/wpf-math/blob/master/src/WpfMath/Atoms/AccentedAtom.cs#L55)?

**Comment by ForNeVeR** [comment]
> Also, we need `NullAtom`, as I understand it. For example, it is being added [here](https://github.com/ForNeVeR/wpf-math/blob/3d700b1109d32384985b9966f39107476cff5fc0/src/WpfMath/Parsers/Matrices/MatrixCommandParser.cs#L92). This is probably connected somehow with an algorithm for which it is necessary that the lines be aligned in length.

Yes, the `NullAtom` was created during the work on matrices, because it looked like a good idea (and I still think it is).

If you don't think it's a good idea to rename `NullAtom` to `EmptyAtom` — okay, this is probably out of scope of your current work anyway. Let's not change it for now.

As I am not still convinced we need some _other_ sort or empty-ish atom, I'll close this issue.

If you still think this is actionable and we need to either change how `NullAtom` works or create another `EmptyAtom` — please leave a comment.

> Question: Should there be `NullAtom` or `EmptyAtom` [here (AccentedAtom.cs#L55)](https://github.com/ForNeVeR/wpf-math/blob/master/src/WpfMath/Atoms/AccentedAtom.cs#L55)?

Well, should it be _any_ atom there? I can only see a call to `StrutBox.Empty`. Does this line currently create any particular problem?

**Comment by rstm-sf** [comment]
> Well, should it be _any_ atom there? I can only see a call to `StrutBox.Empty`. Does this line currently create any particular problem?

I just think that you need to use, for example, NullAtom to simplify the code (but this will entail changes elsewhere).

> As I am not still convinced we need some other sort or empty-ish atom, I'll close this issue.

Ok, np :)  I created issue in order to keep my thoughts in a separate thread.
