### ISSUE TITLE
Test failure in VS2019

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#217]
After being able to overcome #210, I've encountered a test failure:
![image](https://user-images.githubusercontent.com/92793/67144440-7a2d7780-f2a0-11e9-8d62-db3b92db28e1.png)

It looks like VS' test runner uses some slightly outdated (or too modern?) .NET version than we require in our tests.

I believe we should somehow fix that by adding a specialized double serializer for tests. The numbers in question, 0.52778099999999994 and 0.527781, are **exactly equal** (at least my current pwsh session tells me that). We could try to experiment with `.ToString("r")` to use a round-trippable format or something like that. Looks like we unnecessarily expect more precision than is required by the modern approach to double serialization.

**Comment by rstm-sf** [comment]
The problem will disappear if you choose x64 architecture for testing

Thanks to the [so-answer](https://stackoverflow.com/a/51649874)

**Comment by rstm-sf** [comment]
> 0.52778099999999994 and 0.527781

Just round to single precision

**Comment by rstm-sf** [comment]
You can try using the settings file
[Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
