### ISSUE TITLE
Build system of equations

### ISSUE THREAD

**Issue by AlexEternal** [ForNeVeR/wpf-math#264]
I'm trying to build a system of equations, but I can’t translate the second equation to a new line.
Ex worked: `@"\left{ \dot{p_{1}}(t) = \lambda_{21} \cdot p_{2}(t) - \lambda_{12} \cdot p_{1}(t)";`
Ex don't work: `@"\left{ \dot{p_{1}}(t) = \lambda_{21} \cdot p_{2}(t) - \lambda_{12} \cdot p_{1}(t) \\ x2";`

How translate on new line, command: \\newline doesn't work either.
Thanks.

**Comment by ForNeVeR** [comment]
Hello! Try this (checked that it works in v0.8 released this January):
```
\left{\matrix{\dot{p_{1}}(t) = \lambda_{21} \cdot p_{2}(t) - \lambda_{12} \cdot p_{1}(t) \\ x2}\right.
```
![image](https://user-images.githubusercontent.com/92793/80395677-c3a8f000-88dd-11ea-96f1-2221e889a1f2.png)

**Comment by AlexEternal** [comment]
Yes, everything is great. But why do we need `\right.`

**Comment by ForNeVeR** [comment]
It looks like LaTeX works that way: for proper sizing of the braces, it needs to know positions for both left and right braces. I was able to reproduce the same behavior on http://www.texpaste.com/: it always requires both left and right braces. `\right.` is a special kind of empty brace specially for this.
