### ISSUE TITLE
Make a standalone build

### ISSUE THREAD

**Issue by iyutr** [ForNeVeR/wpf-math#294]
Could you please make a standalone .exe, for non-programmers?

**Comment by ForNeVeR** [comment]
What would you want to do with the executable? This is mostly a library for programmers, which would use it to create an executable for the end users.

**Comment by iyutr** [comment]
input: LaTeX formula expression, output: MathML. If it is not related to this project, sorry.
I am looking for a simple little standalone program for this conversion without Javascript, Python, Java, Adobe AIR.

**Comment by ForNeVeR** [comment]
Unfortunately, the current purpose of the project is to _render_ math markup, and not _convert_ from one to another one.

We have plans to eventually support MathML input (#40), but haven't thought anything about conversion, yet.
