### ISSUE TITLE
SystemFontFamilies does not return all FontFamilies in Chinese System

### ISSUE THREAD

**Issue by z0ow** [ForNeVeR/wpf-math#304]
I got an exception thrown in the GetRenderer method when I am trying to change the font name from Arial to 宋体.

![image](https://user-images.githubusercontent.com/20352723/131323145-19b448f3-93e0-4e40-870f-8381c0471d2d.png)
![image](https://user-images.githubusercontent.com/20352723/131323027-4570fbf6-1b4c-4102-883e-2bef232580d6.png)

In the VS debugger, I can confirm the Fonts.SystemFontFamilies only contains 204 elements without 宋体, but it indeed exists in my system and can be created through `var songti = new Font('宋体', 9)`. The songti variable shows it could be found at `System.Drawing.FontFamily`, containing 253 elements.

https://github.com/ForNeVeR/wpf-math/blob/b5d0af65a80e7095addcde247005a8ac1d01b0b6/src/WpfMath/TexFormula.cs#L107

So, using SystemFontFamilies in GetRenderer is aimed to avoid some expectable error or just a bug? Is it possible to change it to the `System.Drawing.FontFamily`?

**Comment by ForNeVeR** [comment]
I'm classifying this as a feature request, since I believe that eventually we'll come to a conclusion that the existing API should be improved for users to be able to pass any fonts directly (not by name).

**Comment by z0ow** [comment]
Hi @ForNeVeR , thanks for your concern.

![image](https://user-images.githubusercontent.com/20352723/131461031-097cb2be-429a-466d-9112-94a8d594f0f9.png)

I am so sorry about confusing the conception of installed and system font. The file of 宋体 is a system font which filename is `SIMSUN.TTC`. The system automatically installs it during OS install, which means it will exist in all Chinese Windows. Now I am confirmed the SystemFontFamilies contains a font which Source is SimSun, and the 宋体 exists in the `FontFamily.FamilyNames.Values`.

![image](https://user-images.githubusercontent.com/20352723/131465263-14a5560e-9262-416f-9be6-c4e74eceed8e.png)

It is probably that this API provides all available alias of Font for different languages. 

For example, the MS Gothic font provides name 'MS Gothic' and 'ＭＳ ゴシック' in FamilyNames with respect to en-us and ja-jp.

![image](https://user-images.githubusercontent.com/20352723/131466422-e8f9e242-8fa6-4961-b897-e1afb9b1636e.png)
![image](https://user-images.githubusercontent.com/20352723/131468446-1863da97-ca17-4da7-aacf-2af65c887567.png)


From the above test, I guess the implementation of the GetSystemFont method can be rewritten as:

```
        internal static SystemFont GetSystemFont(string fontName, double size)
        {
            var fontFamily = Fonts.SystemFontFamilies.First(ff => ff.FamilyNames.Values.Contains(fontName));
            return new SystemFont(size, fontFamily);
        }
```

It is working fine in my system and may is a viable solution 😄 .

![image](https://user-images.githubusercontent.com/20352723/131467992-3105a800-7c42-481d-b8aa-7109c007d965.png)

**Comment by ForNeVeR** [comment]
Thanks a lot for help! I've fixed the issue and will prepare a release soon.
