### ISSUE TITLE
How to generate metric xml file from ttf file

### ISSUE THREAD

**Issue by mhao1999** [ForNeVeR/wpf-math#310]
Hi [ForNeVeR](https://github.com/ForNeVeR), the wpf-math is a cool project, now c# also has a latex formula solution! and I want to integrate it to my desktop application, now could you please have a look at this [issue](https://github.com/opencollab/jlatexmath/issues/98), I still cannot understand how to generate the metrics. thanks!

**Comment by ForNeVeR** [comment]
@mhao1999, the honest answer to this question is, unfortunately, _we don't know_. For now, at least.

The ongoing investigation results are posted in #109. I'll go ahead and close this issue as a duplicate.

Also, you should know that I've already asked this question in the same repository, but got no definitive answer :(

See https://github.com/opencollab/jlatexmath/issues/7.

I'll go and join that discussion.
