### ISSUE TITLE
How can I evaluate the expression?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ForNeVeR/wpf-math#316]
For example, I have 1+1. After I put the equation in the evaluator, I get the results, which is 2. Does this library provide evaluations of math expression? If not, any recommendation for evaluation library?

**Comment by Happypig375** [comment]
https://github.com/asc-community/AngouriMath

**Comment by ForNeVeR** [comment]
Unfortunately, this is out of the scope of this project. Here, we are only looking at rendering of the math (and others, like chemistry) expressions, and not evaluating them. Evaluating may be tricky (especially if the expression is entered in a free format) and not always possible.

You may surely take a look at AngouriMath or other similar libraries.
