### ISSUE TITLE
Add mathematical functions

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#32]
I have the feature request from [Russian F# StackOverflow chat](http://chat.stackexchange.com/rooms/50036/f): add `arctg` and `arcctg` functions. I think that's time to review the functions we have and add those trigonometric functions we still haven't.

Please note that the ordinary notation for tangent is `tan`, but `tg` is also a common extension I think.

Probably these should go into `PredefinedTexFormulas.xml`.

**Comment by alexreg** [comment]
Yes, for sure. At some point it may be advantageous to move from an XML definition to some sort of concise code definition... but I'm not 100% sure yet.

**Comment by gsomix** [comment]
I have updated issue title. We need to add not only trigonometric functions, e.g. \ln, \log, etc.

**Comment by ForNeVeR** [comment]
@alexreg now, when I see the whole picture with that `PredefinedTexFormulas.xml` file, and how you've embedded that small formula DSL directly into the library, that seems like a very smart idea. Take my compliments.

I'm not sure if we want some other formula definition format. What we have seems pretty much what we need, even if XML is a bit "old school".

**Comment by alexreg** [comment]
Okay, fair enough. I generally like to avoid DSLs, but this one does the job fine for now, as you say. A sort of builder-syntax style of defining formulas would be a slight improvement, but maybe not a priority.
