### ISSUE TITLE
Some more project tags

### ISSUE THREAD

**Issue by alexreg** [ForNeVeR/wpf-math#33]
Suggestions to add: dotnet, csharp, tex, mathematics, math/maths, rendering, graphics (include which ones you will)

**Comment by ForNeVeR** [comment]
Alright, I've added `dotnet math tex svg render`. I think that'll be enough for the project discoverability (I imagine guys who're trying to find something like "dotnet formula", "wpf latex", "svg math" so on).

Will add new tags when we have new render mechanisms available (e.g. `avalonia`, `skia`, `gdi+` etc).

**Comment by alexreg** [comment]
Yep, that's fair enough! Cheers.
