### ISSUE TITLE
Problem with Cyrillic

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#35]
Suppose I want to render LaTeX formula including Cyrillic characters: `ЭЭ_E = t \cdot ПДУ`. WPF-Math should fall back to the default font or (preferably) allow the user to specify fallback, and it should actually render the text.

[Texpaste](http://www.texpaste.com/) allows this, for example (and it looks like it uses system-default fallback):
![image](https://cloud.githubusercontent.com/assets/92793/23245526/bdabb274-f9bf-11e6-9697-9a48411e8a4a.png)

Currently WPF-Math fails with the "Unknown character" error on this formula.

**Comment by alexreg** [comment]
This should certainly work within the `\text{...}` command, though it's not so important outside of that, I'd say. However, yes, having a fallback font would be nice.

**Comment by ForNeVeR** [comment]
We now have more information about that problem in #82 and #84, so I'm closing this.
