### ISSUE TITLE
Rename project to XAML-Math

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#360]
I think I made up my mind on naming. I'd like to rename the WPF-Math project to XAML-Math, since it is not entirely WPF-based from now on.

I imagine we'll have three packages:
- `XamlMath.Shared` (the common code for all the platform-specific ones)
- `WpfMath` (no change in name), depending on `XamlMath.Shared`
- `AvaloniaMath` (no change in name from 0.6.0-alpha), also depending on `XamlMath.Shared`
- notably, this also more or less opens ways for us to come up with new names for new frameworks, like `XamarinMath` or `XamlMath.Xamarin` if the former is occupied

So, I don't want to change the name of the main NuGet package, but would like to update the name of the repository and the project.

Before this, we had two different ad-hoc approaches:
- Avalonia branch was using name `SharedMath` for shared code — this is a good name, though I hesitate to use it for something XAML-specific (leave it to Math.NET folks, if you ask me)
- The main branch has used the name `WpfMath.Shared` and we have published 0.13.0 and 0.13.1 with this assembly (not a package dependency, but just a mere assembly)

@alexreg, I'd appreciate your input very much. You have coined the initial name, so I would like you to confirm or deny my decision. It is not set in stone (yet — before we have started publishing the new packages and released 1.0.0, of course), so there's still some time for us to change the name (or maybe just roll with that we have?).

@gsomix, and what would you say?

**Comment by ForNeVeR** [comment]
Another possible option [suggested by Khalid](https://dotnet.social/@khalidabuhakmeh@mastodon.social/109792109952662824): XaMath

**Comment by alexreg** [comment]
Thank you @ForNeVeR, it's very decent of you to consult me on this decision. I've also been glad to see how conscientiously you've maintained the library over the years.

Firstly, I certainly agree a change of name makes sense at this point. Secondly, I remember some discussion some time ago about possibly supporting other UI/rendering frameworks, but I presume the goal is only to support WPF and Avalonia for the foreseeable future? If so, either XAML-Math or XamlMath (both stylisations are perfectly reasonable) work well as names. And of course `XamlMath` as the namespace in either case.

XaMath is a nice snappy name, though personally I favour not abbreviating XAML, for the sake of descriptiveness, which is important for people discovering libraries. That is, if you just happen to come across a library called XAML-Math, and you are a WPF or Avalonia developer, you will immediately have some idea of what this library might do, whereas you might easily overlook a library called XaMath.

**Comment by gsomix** [comment]
@ForNeVeR Personally I prefer boring XAML-Math name. With same justification @alexreg outlined.

**Comment by ForNeVeR** [comment]
> I presume the goal is only to support WPF and Avalonia for the foreseeable future?

Right now — yes. But I'm not against something like MAUI in the future. Maybe Skia renderer will be the next target (though, notably, Skia is used by both Avalonia and MAUI under the covers).

So, well, the current project goals are coupled to XAML frameworks, just because that still seems the main application for productizing the vector-based graphics in .NET UI.

**Comment by ForNeVeR** [comment]
Thanks for your feedback, folks. XAML-Math it is, then.

**Comment by alexreg** [comment]
> So, well, the current project goals are coupled to XAML frameworks, just because that still seems the main application for productizing the vector-based graphics in .NET UI.

Yes, that was my expectation too. Good to confirm.
