### ISSUE TITLE
Nuget version does not include Controls namespace

### ISSUE THREAD

**Issue by torfranz** [ForNeVeR/wpf-math#49]
Hi, I found WpfMath available as a nuget package in VS2015. Although it claims to be v0.2 the whole namespace WpfMath.Controls is missing there, thus making it useless for usage as a WPF control.

Would be great to just reference the nuget package except the need to build my own version from the sources.

**Comment by ForNeVeR** [comment]
@torfranz we haven't yet published the version with the `Controls`; it'll be `v0.3`. Sorry for inconvenience! I think that the new version will be published today or tomorrow.

**Comment by torfranz** [comment]
That would be great :-)

**Comment by ForNeVeR** [comment]
Here it is! https://www.nuget.org/packages/WpfMath/0.3.0
