### ISSUE TITLE
Make delimiters great again

### ISSUE THREAD

**Issue by gsomix** [ForNeVeR/wpf-math#59]
Looks like we don't currently support some of common LaTeX delimiters [1]. We also have some _uncommon_ delimiters, e.g. `\left{` that should be `\left\{` and weird `\left\`.

[1] https://en.wikibooks.org/wiki/LaTeX/Mathematics#Brackets.2C_braces_and_delimiters

**Comment by ForNeVeR** [comment]
See also #60. We have a lot of inconsistencies in our parser; _probably_ we should address them all at once. At least let's start with searching for formal LaTeX grammar!
