### ISSUE TITLE
Command arguments passed without braces

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#60]
Currently `\frac22` fails with an error "missing {" although it actually should render as this:

![image](https://cloud.githubusercontent.com/assets/92793/23340475/84dbbad2-fc69-11e6-950c-5f50ced2a2b3.png)

I suggest we take actual EBNF for LaTeX and implement that instead of relying on intuition :)

**Comment by B3zaleel** [comment]
I changed one of my local versions and it does exactly that, even with the sqrt, underline,frac commands and the script attachments of symbols like (\infty or \oo as in \int_a^\infty). Should I add it to the codebase and create a PR?

**Comment by ForNeVeR** [comment]
Yes, thanks!
