### ISSUE TITLE
Replace XML files with something else

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#65]
We have a bunch of XML files, namely:

- [ ] `DefaultTexFont.xml`
- [ ] `GlueSettings.xml`
- [ ] `PredefinedTexFormulas.xml`
- [ ] `TexFormulaSettings.xml`
- [ ] `TexSymbols.xml`

There's a consensus between current contributors that we need to replace them with something else.

I think that `PredefinedTexFormulas`, `GlueSettings`, `TexFormulaSettings` and `TexSymbols` can be completely replaced by code without problems.

`DefaultTexFont` is a bit different, because it would be too much code to replace it. I'd like to research if we can extract some of its information from the font files we provide. Probably these mappings were originally created by some script we could find and/or rewrite.

After all of the files are gone, we could remove GPL license and release a new version with MIT exclusively.

**Comment by ForNeVeR** [comment]
I've contacted JMathTeX authors and they've granted us the permission to distribute JMathTeX files under MIT license, so I don't see the purpose for this issue anymore.

**Comment by alexreg** [comment]
I agree with your views here. It would be nice to see if some of the information in `DefaultTexFont` is embedded in the font files themselves. The others can be converted into code, like you say. It's good there's no rush on that, however...
