### ISSUE TITLE
Clarify font licensing

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#66]
We're currently providing [some TTF files](https://github.com/ForNeVeR/wpf-math/tree/9236db231ec2528f4bc947697cb7a4c0f812d623/src/WpfMath/Fonts), but I can't find their license (it'd be unusual to find that the fonts are licensed by GPL, too). Some of them looks like [Computer Modern](http://www.ctan.org/texarchive/fonts/cm) (which is distributed under something marked as "Knuth license"). We need to find the source and properly attribute these files.

**Comment by ForNeVeR** [comment]
See also: https://github.com/tonymanou/AndroidLaTeXMath/blob/master/LICENSE#L50-L63

**Comment by alexreg** [comment]
To be honest, I can't remember whether they came with JMathTex (I guess you've already checked that?) or I downloaded them off some free (Creative Commons?) font website. But yes, we should definitely confirm this.

**Comment by alexreg** [comment]
I wonder even if we can find better versions of the fonts, and who knows, maybe the font spacing/gapping issues will disappear?! Of course, I'm well aware it's probably a bug in the code. :)

**Comment by ForNeVeR** [comment]
Yep, I've checked that, and we're using the same files that came from the JMathTeX.

And yes, probably the issue is partially with the fonts themselves. Try to save the formula in question to SVG and look at it with maximal zoom. You'll notice some weirdness in the places where there're visible gaps in #52.

I'll check that. The first idea I have is to compare our fonts with the ones from LaTeXMath — probably the guys there have already solved the issue.
