### ISSUE TITLE
Documentation about dealing with XML

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#70]
I want to generate `DefaultTexFont.xml` from the TTF files we have.

[Comments](https://github.com/opencollab/jlatexmath/issues/7) from jlatexmath maintainer were helpful, but I'm still struggling with that. Will document after I find everything out.

**Comment by B3zaleel** [comment]
There's a python library called fonttools. It can extract the information from an open type font, such as the width(to 3decimal places), the name of the character, the Unicode code point of the character, etc however, the Kern property and a few others cannot be generated.

**Comment by ForNeVeR** [comment]
@B3zaleel yes, I have been using fonttools (also known as `ttx`) with some limited success. See [the corresponding documentation](https://github.com/ForNeVeR/wpf-math/blob/master/docs/prepare-font.md) on the current state of the matter.
