### ISSUE TITLE
Support UTF8

### ISSUE THREAD

**Issue by abozanona** [ForNeVeR/wpf-math#82]
Can you support UTF8 symbols? I can't add symbols from other languages than English!

**Comment by ForNeVeR** [comment]
Thanks for the report. That issue is definitely on the radar, see #35. In the meantime, please try to use `\text{...}` workaround as suggested in https://github.com/ForNeVeR/wpf-math/issues/35#issuecomment-282025947.

**Comment by alexreg** [comment]
Generally, the only symbols allowed in maths are the letters from the Latin, Greek, and occasionally Hebrew alphabets. Do we really need general support for other character sets?

**Comment by ForNeVeR** [comment]
Yes, we need (if possible). I'm using Cyrillic in my maths all the time :)

**Comment by alexreg** [comment]
Hmm, I see. I guess it's only something done in countries where Cyrillic is the ordinary script anyway... explains why we never see it in the West. I wonder if Chinese characters are used, even...

**Comment by ForNeVeR** [comment]
These are extremely rare in international papers, but they aren't uncommon in the local documentation (especially in government regulations and patent descriptions).

**Comment by ForNeVeR** [comment]
Please note that in my experience TeX doesn't allow any non-standard characters outside of the `\text{}` blocks, so I'm not sure if we **have** to implement that as stated in #35. We'll probably need some additional research in that (e.g. how LuaTeX or XeTeX handles that; what about MathJAX, so on). We're open to suggestions.

**Comment by abozanona** [comment]
I tried to use `\text{SOME TEXT HERE}` but it didn't work: `\text{number of cats}`

If it's not allowed to use symbols other than the standard ones, maybe you could declare an array of the positions of non-standard symbols in the equation so We can replace it in the string by `\text{number of cats}`

**Comment by alexreg** [comment]
Can you post exactly what you're doing? The `\text{...}` command works just fine for us!

**Comment by abozanona** [comment]
I've downloaded the `WpfMath.dll` file to my project from [NuGet Manager](https://www.nuget.org/packages/WpfMath/) V0.3.0, I'm using vb.net

    Private Function ParseFormula(input As String) As TexFormula
        ' Create formula object from input text.
        Dim formula As TexFormula = Nothing
        Try
            txtEquation.ForeColor = Color.Black
            formula = Me.formulaParser.Parse(input)
        Catch ex As Exception
            txtEquation.ForeColor = Color.Red
        End Try

        Return formula
    End Function

When I try to parse `\text{abc}` it gives me the exception `Unknown symbol or command or predefined TeXFormula: 'text'`

**Comment by abozanona** [comment]
I tried to type the same command on the application I downloaded from here and it gives me the same error
![image](https://cloud.githubusercontent.com/assets/12738028/26277821/bf6f577e-3d98-11e7-8514-28b39f6d1ca8.png)

**Comment by alexreg** [comment]
Try 0.3.1 for a start. :-)

**Comment by abozanona** [comment]
I tried now to upgrade to `0.3.1` from NuGet manager but it didn't work either.

**Comment by alexreg** [comment]
Okay. @ForNeVeR can answer this hopefully. You've definitely set something up wrong on your end, however...

**Comment by ForNeVeR** [comment]
Well, it won't be an easy task. I've started the work in branch, and currently I'm struggling with `TexFontInfo`. It seems that we'll need to somehow extract `TexFontInfo` from the real system fonts.

**Comment by ForNeVeR** [comment]
Well, guys, we have rudimentary support for UTF-8 now.

I couldn't do everything in one go, so now new features in that direction will depend on our dear users' needs. Feel free to open new tickets regarding concrete features we lack.

As an example, this will now work:

```\frac{\text{ЭЭ}}{\text{ЭЭ}_{2}}```
