### ISSUE TITLE
Explicate copyright permission of jmathtex

### ISSUE THREAD

**Issue by generateui** [ForNeVeR/wpf-math#87]
While the copyright statement on the readme.md notes that the files from the JMathTeX project are licensed in MIT, this repository does not contain the permission notice. 

I ask about this matter [here](https://opensource.stackexchange.com/questions/5579/copyright-license-grants-of-gplv2-in-mit-project/5580#5580).

Could you please add a communication trace of this permission to this repository, or a link to this permission? Our corporate overlords may then accept use of this library. Lots of thanks in advance!

**Comment by ForNeVeR** [comment]
Hello. I've personally contacted with JMathTeX authors, and they have granted the permission. Here's a quotation from Dr. Kris Coolsaet's letter I received at March, 1, 2017:

![image](https://user-images.githubusercontent.com/92793/26868345-e80ac08a-4b92-11e7-8799-80472968568c.png)

Is that enough? What else could I do to state it more clearly in the documentation?

**Comment by generateui** [comment]
IANAL, but going on the StackExchange answer this looks like it will be enough. Thanks you for your reply, and thanks you for your speed.

**Comment by ForNeVeR** [comment]
Okay, I consider the issue resolved.
