### ISSUE TITLE
Bar alignment

### ISSUE THREAD

**Issue by tqmitaca** [ForNeVeR/wpf-math#88]
In my statistical application I need to show a double bar over one character like in image

![doublebarx](https://user-images.githubusercontent.com/7223615/30101729-b5c58f54-92ed-11e7-8305-1f3e3e410761.png)
 
I try  the syntax \bar{\bar{X}} but the bars are not aligned

![alignbar](https://user-images.githubusercontent.com/7223615/30101883-31ba8312-92ee-11e7-904e-204b24acf779.png)

**Comment by gsomix** [comment]
@tqmitaca Thanks for the report! I'm going to fix it ASAP.

**Comment by gsomix** [comment]
All kudos to @ForNeVeR!

**Comment by ForNeVeR** [comment]
FYI: we will publish the new release to NuGet today.
